-- Add new columns to users table
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "zmguserid" VARCHAR(190);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "pass" VARCHAR(190);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "usertype" VARCHAR(80);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "rowId" VARCHAR(80);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "region" VARCHAR(120);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "regionhrd" VARCHAR(120);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "access" VARCHAR(120);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "status" VARCHAR(80);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "login" VARCHAR(80);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "userRegion" VARCHAR(255);

-- Modify name column to VARCHAR(230)
ALTER TABLE "users" ALTER COLUMN "name" TYPE VARCHAR(230);